# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Products Service Stack
Transform: AWS::Serverless-2016-10-31

Parameters:
#Stack name
  stackName:
    Type: String
    Default: ''

Resources:
  ProductFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: ProductFunction
      Handler: dist/productlambda.handler
      Runtime: nodejs16.x
      MemorySize: 128
      Timeout: 100
      Architectures:
        - x86_64
      Description: First create product call
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref ProductsTable
      Events:
        Nest:
          Type: Api 
          Properties:
            Path: /{proxy+}
            Method: any

  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Products
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: title
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: title
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

Outputs:
  NestApi:
    Description: "API Gateway endpoint URL for Prod stage for a Nest function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  
  ProductsTable:
    Value: !Ref ProductsTable
    Description: Table for storing products data.